import type { Metadata } from 'next';
import LegalLayout, { Section } from '../legal/LegalLayout';
import { SITE_CONFIG } from '@/lib/site';

export const metadata: Metadata = { title: 'Privacy Policy', description: 'How Skolvo handles website, account, product, support, and future billing data.' };

export default function PrivacyPage() {
  return <LegalLayout eyebrow="Legal" title="Privacy Policy" updated="31 August 2026" summary="This policy explains data handling for the public website and, where the relevant workflow is used, Skolvo Agent, CampusNova, and SignalWatch.">
    <Section heading="1. Who is responsible"><p>Skolvo is a software brand operated by <strong>{SITE_CONFIG.legalOwnerName}</strong>, an individual / sole proprietor in {SITE_CONFIG.legalCountry}. Contact <a className="link-underline" href={`mailto:${SITE_CONFIG.supportEmail}`}>{SITE_CONFIG.supportEmail}</a> about privacy or your data.</p></Section>
    <Section heading="2. Data we process"><p>Depending on the service you use, we may process account details and email; contact and support messages; waitlist product and role selections; usage and activity records; and security logs needed to operate the service.</p><p>Product data may include CV/resume files and job-profile information in Skolvo Agent; student-verification information when a discount is requested; institution, workspace, student, teacher, fee, and report data in CampusNova; and client watch configurations and public-record matches in SignalWatch. We process only the categories relevant to the workflow being used.</p></Section>
    <Section heading="3. Why we process it"><p>We use data to provide and secure accounts and software workflows, apply usage allowances, respond to support, verify student eligibility, produce requested outputs, improve reliability, prevent misuse, keep necessary records, and meet legal obligations. We do not sell personal data or share it for advertising.</p></Section>
    <Section heading="4. Website storage and analytics"><p>The site stores a versioned local preference in your browser when you dismiss an announcement so it does not appear on every reload. Contact and interest forms store the information you submit. The current site does not use advertising trackers or third-party behavioural analytics and does not add marketing cookies for these features.</p></Section>
    <Section heading="5. Payments"><p>When Paddle Billing is activated, billing identifiers, subscription status, transaction references, and limited buyer details may be exchanged with Paddle as payment provider and Merchant of Record. Payment-card details will be collected and processed by the payment provider and are not intended to be stored directly by Skolvo.</p></Section>
    <Section heading="6. Providers and international processing"><p>We use service providers where needed for hosting, managed databases, authentication, communications, and eventually payments. Data may therefore be processed outside your country. We select providers and safeguards appropriate to the service and will update material processor information as production services are activated.</p></Section>
    <Section heading="7. Retention"><p>We retain information only while needed to provide the service, maintain security and transaction records, resolve disputes, or meet legal obligations. Contact and waitlist records are removed when no longer needed or upon a valid deletion request. Product retention depends on account status, configuration, backups, and applicable law; deletion may take a limited period to propagate through backups.</p></Section>
    <Section heading="8. Security"><p>We use reasonable technical and organisational safeguards appropriate to the product stage, including access controls and data minimisation. No internet service can guarantee absolute security. Please report a suspected issue through our <a className="link-underline" href="/security">Security page</a>.</p></Section>
    <Section heading="9. Your choices and rights"><p>You may ask to access, correct, export, or delete personal data, object to or restrict certain processing, or withdraw consent where processing relies on it. Some records may need to be retained for security, legal, or transaction purposes. Contact us at {SITE_CONFIG.supportEmail}; we may need to verify your identity before acting.</p></Section>
    <Section heading="10. Changes"><p>We will update the date above when this policy changes. Material changes affecting account holders will be communicated through a reasonable product or email notice where appropriate.</p></Section>
  </LegalLayout>;
}
