import type { Metadata } from 'next';
import Link from 'next/link';
import LegalLayout, { Section } from '../legal/LegalLayout';
import { SITE_CONFIG } from '@/lib/site';

export const metadata: Metadata = { title: 'Terms of Service', description: 'Terms governing Skolvo software products, free allowances, subscriptions, and responsible use.' };

export default function TermsPage() {
  return <LegalLayout eyebrow="Legal" title="Terms of Service" updated="31 August 2026" summary="These terms govern the Skolvo website, usage-limited free access, product evaluations, and any paid software subscription that becomes available.">
    <Section heading="1. Operator and agreement"><p><strong>{SITE_CONFIG.legalOperatorDisclosure}</strong> By using a service, creating an account, or purchasing a subscription, you agree to these terms. If acting for an organisation, you confirm that you have authority to bind it.</p></Section>
    <Section heading="2. Services and current status"><p>Skolvo develops three software products: Skolvo Agent for job-opportunity workflows, CampusNova for academy administration, and SignalWatch for regulatory information monitoring. Product pages identify whether a workflow is implemented, in private prototype, being validated on historical data, or available for paid use. Features described as planned, prototype, beta, or coming soon are not commitments to a release date.</p></Section>
    <Section heading="3. Accounts and user responsibilities"><p>You must provide accurate account information, protect credentials, and promptly report suspected unauthorised access. You are responsible for activity under your account and for having the rights and permissions needed to upload or configure any content.</p></Section>
    <Section heading="4. Acceptable use"><p>You may not misuse the services, violate law or third-party rights, probe or disrupt systems without authorisation, access another user&apos;s data, upload malicious code, evade usage limits, send abusive or unsolicited communications, or resell the service without written permission. Biometric or student information must not be processed without the consent and lawful basis required where you operate.</p></Section>
    <Section heading="5. Free plans and subscriptions"><p>Free access is usage-limited, not a time-limited trial, and does not require a payment card. Current allowances and paid prices appear on the <Link href="/pricing" className="link-underline">Pricing page</Link>. We may adjust future limits or prices with clear notice; an active paid subscription will be handled according to the purchase terms shown at checkout.</p></Section>
    <Section heading="6. Billing, cancellation, and refunds"><p>When paid checkout is activated, subscriptions will renew at the displayed interval until cancelled. You may cancel future renewal through the billing mechanism made available to you. Cancellation normally takes effect at the end of the paid period. Refund requests are governed by our <Link href="/refund-policy" className="link-underline">Refund Policy</Link>, the applicable Merchant of Record buyer terms, and mandatory consumer law.</p></Section>
    <Section heading="7. Product-specific boundaries"><p><strong>Skolvo Agent</strong> assists with discovery, fit and eligibility review, preparation, and tracking. It does not guarantee an application, interview, offer, employment, or the accuracy of third-party job information. Users remain responsible for reviewing and approving actions.</p><p><strong>CampusNova</strong> supports academy administration workflows but does not guarantee academic, attendance, financial, or institutional outcomes. Institutions remain responsible for their records, permissions, policies, and legal obligations.</p><p><strong>SignalWatch</strong> is information and monitoring software using public regulatory sources. It is not legal, medical, compliance, or regulatory advice. Public records may be delayed, amended, or incomplete; users remain responsible for professional review and decisions. Historical/sample analysis is distinct from scheduled production monitoring.</p></Section>
    <Section heading="8. Intellectual property and user content"><p>Skolvo and its software, design, and documentation remain the property of the operator and licensors. You retain ownership of content you provide and grant us only the permission needed to host, process, protect, and return it for the service. You confirm that you have the right to provide that content.</p></Section>
    <Section heading="9. Availability, beta features, and third parties"><p>We do not promise uninterrupted or error-free access. We may change or withdraw unfinished features and will describe material availability limits honestly. Services may rely on hosting, databases, public data sources, authentication, and payment providers; their systems and terms may also apply.</p></Section>
    <Section heading="10. Disclaimers and limitation"><p>To the extent permitted by law, services are provided as available without implied warranties of fitness, uninterrupted operation, or a particular outcome. Our aggregate liability relating to a paid service is limited to fees paid for that service in the 12 months before the claim. We are not liable for indirect or consequential loss. Nothing excludes liability that cannot legally be excluded, including fraud or mandatory consumer rights.</p></Section>
    <Section heading="11. Suspension, termination, and governing law"><p>You may stop using a free service or cancel a subscription. We may suspend access for material misuse, security risk, or non-payment and will give notice where reasonably possible. These terms are governed at a high level by the laws of Pakistan, without removing mandatory rights you have under applicable consumer law.</p></Section>
    <Section heading="12. Contact"><p>Questions or legal notices may be sent to <a className="link-underline" href={`mailto:${SITE_CONFIG.supportEmail}`}>{SITE_CONFIG.supportEmail}</a>.</p></Section>
  </LegalLayout>;
}
